name: Data Driven
description: Using Data to Drive Decisions
meta_description: "A Blog About Data-Driven Decision Making"
baseurl: '/data-driven/'

markdown: redcarpet
pygments: true
logo: '/images/vapor_logo.png'
paginate: 3

author:         
  name: 'Jordan Engbers'
  website: 'datadriven.guru'
  bio: 'A generalist data-junkie'
  image: 'http://www.gravatar.com/avatar/da65eb9df5c01e7d9ab7e636a4275f1d.png'

# Details for the RSS feed generator
url:            'blog url'
